116. Implement application overview card and table
cartesi/rollups-explorer pull request #125
Opened 2024-03-05 05:58 UTC by dandheedge

Close #116

2024-03-12 14:43 UTC, nevendyulgerov commented on apps/web/src/components/applications/applications.tsx
> +                    <>
No need for this extra fragment.

2024-03-12 14:47 UTC, nevendyulgerov commented on apps/web/src/components/applications/applications.tsx
> +                <Stack
Maybe we can extract this `Stack` with its props to a separate component to prevent code duplication and use it for both `UserApplications` and `Applications`?

2024-03-12 15:49 UTC, nevendyulgerov commented on apps/web/src/components/entriesSummary.tsx
> +        },
Let's use the `pause` option here with `isConnected`:

```
const { address, isConnected } = useAccount();
const [query] = useStatsApplicationsOwnerQuery({
    variables: {
        ...
    },
    pause: !isConnected
});
````

We shouldn't show results for user owned applications until the user's wallet is connected.

2024-03-12 15:50 UTC, nevendyulgerov commented on apps/web/src/components/applications/applications.tsx
> +            after: "1",
Do we need the `after` variable here? This will get applications after the first one.

2024-03-12 15:56 UTC, nevendyulgerov commented on apps/web/src/components/entriesSummary.tsx
> +            applicationId: address,
Please use here:

```
applicationId: address?.toLowerCase()
```

Otherwise, you won't get correct results for the owner applications.

2024-03-12 20:32 UTC, nevendyulgerov commented on apps/web/src/components/applications/applications.tsx
> +            after: "1",
Another thing that I noticed but I'm not sure if it's something we should address is that on sunodo-generated dapp, the explorer api graphql (at http://localhost:8080/explorer-api/graphql) and `ApplicationsConnection` query doesn't support the `timestamp` field. So, in this case I'm getting a `400` error with message:

```
"Cannot query field \"timestamp\" on type \"Application\"."
```

Here's a screenshot:
![Screenshot 2024-03-12 at 22 27 49](https://github.com/cartesi/rollups-explorer/assets/6005179/be7bc44e-8eba-4236-bcfb-2c8433604210)


And here's the same but on sepolia:
![Screenshot 2024-03-12 at 22 19 50](https://github.com/cartesi/rollups-explorer/assets/6005179/bd7b8c4b-cfbf-4e8e-bead-1563e2cf4076)

CC @brunomenezes

2024-03-14 05:27 UTC, dandheedge commented on apps/web/src/components/applications/applications.tsx
> +            after: "1",
> Do we need the `after` variable here? This will get applications after the first one. Also, I see that on sepolia, certain owners (like `0xf05d57a5bed2d1b529c56001fc5810cc9afc0335`) have more than `20` applications:
> 
> ![Screenshot 2024-03-12 at 22 19 50](https://private-user-images.githubusercontent.com/6005179/312225276-c3bb2bfa-98b0-45be-a699-4039d7c2b7ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzOTExNDIsIm5iZiI6MTcxMDM5MDg0MiwicGF0aCI6Ii82MDA1MTc5LzMxMjIyNTI3Ni1jM2JiMmJmYS05OGIwLTQ1YmUtYTY5OS00MDM5ZDdjMmI3YWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMDQzNDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzIyNzZjZWExZDBmYTg3ZmQwZjY5ZDA3OWI5ZDczZWYxNDE1OWNkZTFmZTMwMzljZmVlNDU3Yjg3YTY5ZjZmMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1nneHerRz1JHfIvbFJdb8u5fxij0D_bwNbsDJ5V9xUY)
> 
> I think we'll need pagination for the `UserApplicationsTable` component.

@nevendyulgerov, initially, I want to keep it simple just to display the 20 applications a user has. Do you think we need another pagination component for UserApplicationsTable, or can we display all the data at once? My concern with adding another pagination component is that the query parameters might become bloated.

2024-03-17 22:25 UTC, brunomenezes commented on apps/web/src/components/applications/applications.tsx
> +            after: "1",
> Another thing that I noticed but I'm not sure if it's something we should address is that on sunodo-generated dapp, the explorer api graphql (at http://localhost:8080/explorer-api/graphql) and ApplicationsConnection query doesn't support the timestamp field. So, in this case I'm getting a 400 error with message:

The rollups-explorer (UI and API) docker images available are probably old, but they work together. The latest ones (0.9.0 and 0.4.0) are merged on Sunodo's base code, but I am not sure if they have already released the new version, `0.11.0`. So using a local dev rollups-explorer running in parallel with sunodo-cli (i.e. sunodo run) you may have expected troubles. Here is what I do, if you are on a Mac and installed Sunodo-cli using `homebrew` you can go to `/opt/homebrew/Cellar/sunodo/SUNODO_VERSION_HERE/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-explorer.yaml` and replace the tags for API and UI.  In the rollups-explorer project's root you can do a `docker buildx bake` that will build a `cartesi/rollups-explorer` tag `devel` so you can add that tag in the Sunodo docker-compose file I mentioned and you have the "dev" version running if that is necessary. 


> @nevendyulgerov, initially, I want to keep it simple just to display the 20 applications a user has. Do you think we need another pagination component for UserApplicationsTable, or can we display all the data at once? My concern with adding another pagination component is that the query parameters might become bloated.

@dandheedge, Let me add two cents here. This is a list displayed "temporarily" i.e. only related to the account address of the connected wallet, so without a connected wallet it should not have a list to show. Nevertheless, pagination is important. 

that said: 
1. What would be the pros/cons of having the pagination tracked by the query-params? 
2. What would be the pros/cons of having the pagination not tracked on the query-params but only in its own local component/hook? 
3. Why would you choose one over another?

2024-03-18 00:33 UTC, dandheedge commented on apps/web/src/components/applications/applications.tsx
> +            after: "1",
> The rollups-explorer (UI and API) docker images available are probably old, but they work together. The latest ones (0.9.0 and 0.4.0) are merged on Sunodo's base code, but I am not sure if they have already released the new version, `0.11.0`. So using a local dev rollups-explorer running in parallel with sunodo-cli (i.e. sunodo run) you may have expected troubles. Here is what I do, if you are on a Mac and installed Sunodo-cli using `homebrew` you can go to `/opt/homebrew/Cellar/sunodo/SUNODO_VERSION_HERE/libexec/lib/node_modules/@sunodo/cli/dist/node/docker-compose-explorer.yaml` and replace the tags for API and UI. In the rollups-explorer project's root you can do a `docker buildx bake` that will build a `cartesi/rollups-explorer` tag `devel` so you can add that tag in the Sunodo docker-compose file I mentioned and you have the "dev" version running if that is necessary.

@brunomenezes here are my thoughts on your question:

#### Pagination Tracked by Query-Params

**Pros**

- Users can bookmark or share URLs that maintain the state of the application.

**Cons**

- In the `/applications` page, the page already have the query-params for **All Applications** table. Adding more pagination with tracked query-params will increase the complexity on the url and the state handling as well.

#### Pagination With Local Hook

**Pros**

- Simplifies state management within the component and results in a cleaner URL.
- [Stake Application](https://explorer.cartesi.io/) has already implemented this method, suggesting it is a reliable approach.

**Cons**

- Users cannot bookmark or share URLs that preserve the application's state.

I prefer using a local hook for pagination since the table only displays data related to the user's connected address, avoiding unnecessary complexity.

2024-03-18 00:37 UTC, brunomenezes requested changes

2024-03-18 00:37 UTC, brunomenezes commented on apps/web/graphql/queries.graphql
> +    applicationsConnection(orderBy: id_ASC, where: {owner_startsWith: $applicationId}) {
Hey @dandheedge, The `*_startsWith` has implications for API queries. It will translate into a `Like` operator, and it makes sense when doing a query search (To some extent), but I think using `*_eq` is better here since the value is known and should `exact match`. _As a side note, as we start having more queries, we should evaluate the creation of new indexes on the API side._

2024-03-18 00:37 UTC, brunomenezes commented on apps/web/graphql/queries.graphql
> +    applicationsConnection(orderBy: $orderBy, first: $limit, after: $after, where: {owner_startsWith: $ownerId}) {
Same I mentioned above regarding the `*_startsWith`

2024-03-18 00:37 UTC, brunomenezes commented on apps/web/src/components/applications/userApplicationsTable.tsx
> +            h={"40vh"}
@dandheedge, with that fixed, when you have no applications (my case), you have a reasonable length of empty space, pushing the `All applications`  further down without a good reason.

2024-04-05 00:06 UTC, brunomenezes commented
@dandheedge, A few PRs were merged, could you rebase?

2024-04-21 22:42 UTC, brunomenezes requested changes

2024-04-21 22:42 UTC, brunomenezes commented on apps/web/src/components/applications/applications.tsx
> + * @returns Component to wrap Application or UserApplication coponent
small typo here

2024-04-21 22:42 UTC, brunomenezes commented on apps/web/src/components/applications/applications.tsx
> +            ownerId: "0xf05d57a5bed2d1b529c56001fc5810cc9afc0335".toLowerCase(),
@dandheedge, hardcoded address here. Currently, that is what I see when changing accounts. 👇 

![my-applications-hardcoded-address](https://github.com/cartesi/rollups-explorer/assets/1239768/de9000b9-32f2-42d1-a1c2-8eac5c3b3924)

2024-04-25 01:35 UTC, brunomenezes requested changes
Rebase the branch.

2024-04-25 01:35 UTC, brunomenezes commented on apps/web/src/components/applications/userApplicationsRow.tsx
> +                        href={`/applications/${appId}`}
@dandheedge, I saw you rebase and have Neven's latest code changes related to the App's inputs. This link need to be updated accordingly.

2024-04-29 22:38 UTC, merged