#130 Upgrade rainbowkit wagmi viem packages
cartesi/rollups-explorer pull request #140
Opened 2024-03-18 13:16 UTC by nevendyulgerov

2024-03-18 15:47 UTC, nevendyulgerov commented on packages/ui/src/ERC20DepositForm.tsx
> +    useWatchQueryOnBlockChange(erc20.queryKey);
The `watch` property is deprecated in `wagmi 2.x` so we now have to track block number changes ourselves and then invalidate the cache for the relevant query so it's re-executed again.

2024-03-18 15:55 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/InputDetailsContext.tsx
> +    keys as (a: unknown) => unknown,
TS errors popped up on those two lines so I quickly fixed them.

2024-03-18 21:57 UTC, brunomenezes commented on docker/Dockerfile
> +RUN apk add --update --no-cache python3 build-base gcc && ln -sf /usr/bin/python3 /usr/bin/python
Can you run a container and the app from that image without problems?

2024-03-18 22:02 UTC, brunomenezes commented on packages/rollups-wagmi/wagmi.config.ts
> +        {
I saw they moved to Viem (They also develop and maintain it).

2024-03-18 23:04 UTC, brunomenezes commented on packages/ui/src/hooks/useWatchQueryOnBlockChange.ts
> +    queryKey: readonly unknown[],
I wonder whether or not we have a way to check the type we expect from the `query key`.  By TanStack docs it says it should be an array of a single string, multiple strings or other complex objects as far as it is serializable (multiple possibilities). But, I imagine wagmi is creating the `queryKey`, just wondering if we can specify the type here based on how wagmi generates these keys. Any thoughts?

2024-03-21 11:50 UTC, nevendyulgerov commented on docker/Dockerfile
> +RUN apk add --update --no-cache python3 build-base gcc && ln -sf /usr/bin/python3 /usr/bin/python
Hi, @brunomenezes , can you please let me know what are the steps to do that? I looked into the readme file but there isn't any info there about this.

2024-03-21 12:00 UTC, nevendyulgerov commented on packages/rollups-wagmi/wagmi.config.ts
> +        {
@brunomenezes , I didn't find a matching plugin/export from `viem` package for this. Searched in their github repo for related information but again didn't find anything. Can you share a link or reference to that plugin please?

2024-03-21 12:17 UTC, nevendyulgerov commented on packages/ui/src/hooks/useWatchQueryOnBlockChange.ts
> +    queryKey: readonly unknown[],
I think wagmi is directly using the queryKey type coming from react-query which is:

```
type QueryKey = ReadonlyArray<unknown>;
```

![Screenshot 2024-03-21 at 14 14 46](https://github.com/cartesi/rollups-explorer/assets/6005179/7dae28c9-87eb-4063-92f3-e58c2627b605)

![Screenshot 2024-03-21 at 14 14 57](https://github.com/cartesi/rollups-explorer/assets/6005179/7f018e46-b13c-441e-8d4d-4b625d33c7b9)

![Screenshot 2024-03-21 at 14 15 00](https://github.com/cartesi/rollups-explorer/assets/6005179/b23b69dd-d6e4-4cb5-ae7e-7a81aeeaa97d)

So I don't think we can make it more specific.

2024-03-25 01:26 UTC, brunomenezes commented on packages/rollups-wagmi/wagmi.config.ts
> +        {
I am not saying that they moved the `/cli` part anywhere, but rather that they removed it and left you to use the `viem` available ABIs.

2024-03-25 01:31 UTC, brunomenezes commented on docker/Dockerfile
> +RUN apk add --update --no-cache python3 build-base gcc && ln -sf /usr/bin/python3 /usr/bin/python
We have a `docker-bake.hcl` file in the project's root.
Have a look inside that file, and you can change the `ENVIRONMENT` args to `sepolia` (currently set as `sunodo`).

**Required: Docker-desktop.**
To build the image: `docker buildx bake` 

After building the image you should be able to see the image generated. Run it on a docker container and have a spin.

2024-03-25 11:47 UTC, nevendyulgerov commented on docker/Dockerfile
> +RUN apk add --update --no-cache python3 build-base gcc && ln -sf /usr/bin/python3 /usr/bin/python
Thanks @brunomenezes , I ran a docker container and tested the app from there. Everything looks good on my end.

2024-03-26 07:48 UTC, brunomenezes requested changes

2024-04-02 02:02 UTC, brunomenezes approved these changes

2024-04-02 02:03 UTC, merged