#156 Voucher content decoding
cartesi/rollups-explorer pull request #161
Opened 2024-04-22 20:53 UTC by dandheedge

Close #156

2024-05-26 21:01 UTC, brunomenezes commented
@dandheedge how is that going? 

@nevendyulgerov is the **drawingcanvas** you productiv-e deployed generating vouchers? is that in Sepolia?

2024-06-06 13:27 UTC, nevendyulgerov commented on packages/ui/src/hooks/useDecodeVoucherPayload.ts
> +    }, [destination, payload]);
Missing dependency `content` here.

2024-06-06 13:35 UTC, nevendyulgerov commented on packages/ui/src/hooks/useDecodeVoucherPayload.ts
> +    useEffect(() => {
I would refactor this a bit to decouple the effect and the `decodePayload` function:

```
const decodePayload = useCallback(async () => {
    setLoading(true);
    try {
        const decodedData = await decodeVoucherPayload({
            destination,
            payload,
        });
        setData(decodedData);
    } catch (err) {
        setError(
            err instanceof Error
                ? err
                : new Error(
                      "An error occurred while decoding the voucher payload",
                  ),
        );
        setData(payload); // Fallback value for raw value.
    } finally {
        setLoading(false);
    }
}, [destination, payload]);

useEffect(() => {
    if (typeof content === "string") {
        setData(content);
    } else {
        decodePayload().catch(() => undefined);
    }
}, [content, decodePayload, destination, payload]);
```

Please note the error message (I tweaked it a bit to make it more detailed) and also I added a `catch` to the `decodePayload()` invocation (I was getting a warning about ignoring the returned promise. 

Finally, in the effect, I'm checking if the content is of type string, not the other way around. I find it easier to write/read conditions starting with the positive case.

2024-06-06 13:37 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/VoucherContent.tsx
> -
I don't think we need to touch this file if no code is changed in it. Please revert this change to reduce the PR's footprint.

2024-06-06 13:40 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/Content.tsx
> +const LoadingState: React.FC = () => {
I'm getting a `Referenced UMD global variable` warning here, please import `FC` from `react` package instead and then refactor like this:

```
const LoadingState: FC = () => {...}
```

2024-06-06 13:40 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/Content.tsx
> +export const VoucherDisplayContent: React.FC<VoucherDisplayContentProps> = ({
Same for `React.FC` as above.

2024-06-06 13:42 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/Content.tsx
> +    if (type === "json") {
Instead of having multiple return statements I'd simplify this to:

```
return (
    <>
        {loading ? (
            <LoadingState />
        ) : type === "json" ? (
            <JsonInput
                rows={10}
                value={
                    (error as unknown as string) ??
                    (JSON.stringify(data) as string)
                }
                readOnly
                placeholder="No content defined"
            />
        ) : type === "text" ? (
            <Textarea
                rows={10}
                value={
                    (error as unknown as string) ??
                    (JSON.stringify(data) as string)
                }
                readOnly
                placeholder="No content defined"
            />
        ) : (
            <Textarea
                rows={10}
                value={content.payload as Hex}
                readOnly
                placeholder="No content defined"
            />
        )}
    </>
);
```

Single return statement and the conditions are baked directly in the jsx code.

2024-06-06 13:44 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/Content.tsx
> +export const DisplayContent: React.FC<FCContentType> = ({ type, content }) => {
Same for `React.FC` as above. Also, here we can refactor the logic slightly:

```
return (
    <>
        {typeof content === "string" ? (
            <DefaultDisplayContent type={type} content={content} />
        ) : (
            <VoucherDisplayContent type={type} content={content} />
        )}
    </>
);
```

2024-06-06 13:49 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/Content.tsx
> +                    (error as unknown as string) ??
Can we just do this instead:

```
value={error?.toString() ?? JSON.stringify(data)}
```

2024-06-06 13:49 UTC, nevendyulgerov commented on packages/ui/src/InputDetails/Content.tsx
> +                    (error as unknown as string) ??
Same as above for the `value` prop.

2024-06-06 13:51 UTC, nevendyulgerov commented on packages/decoder/src/index.ts
> +    destination: `0x${string}`;
Please use `Address` from `viem` instead for those types.

2024-06-06 13:52 UTC, nevendyulgerov commented on packages/decoder/src/index.ts
> +    try {
No need for this `try...catch` block here. Let's leave the error handling to the callee (`useDecodeVoucherPayload`) instead.

2024-06-06 13:53 UTC, nevendyulgerov commented on packages/decoder/src/index.ts
> +        const res = await decodeFunctionData({
`decodeFunctionData` is not `async`, thus we don't need the `await` keyword here.

2024-06-06 13:54 UTC, nevendyulgerov commented on packages/decoder/src/index.ts
> +            data: payload as `0x${string}`,
No need for type assertion here.

2024-06-06 13:58 UTC, nevendyulgerov commented on packages/decoder/test/decodeVoucherPayload.test.ts
> +import { decodeVoucherPayload } from "../src/index";
Import can be shortened to `../src`

2024-06-06 13:59 UTC, nevendyulgerov requested changes
I left some comments with suggestions for general improvements. I'll do another round of testing of the actual feature later today and tomorrow.

2024-06-25 00:06 UTC, brunomenezes commented
I will take over that one.

2024-07-14 21:57 UTC, closed without merging