#186 Add input completion status
cartesi/rollups-explorer pull request #198
Opened 2024-06-04 17:32 UTC by nevendyulgerov

2024-06-05 14:02 UTC, nevendyulgerov commented on docker/Dockerfile
> +RUN yarn global add turbo@1.13.3
The build was failing with the following errors both from this branch and from `main`:

![Screenshot 2024-06-05 at 16 12 32](https://github.com/cartesi/rollups-explorer/assets/6005179/a3174d17-7d7b-4786-a5a0-06b718b10e6a)

![Screenshot 2024-06-05 at 16 12 57](https://github.com/cartesi/rollups-explorer/assets/6005179/0741ef68-b390-4c30-b555-2065d1b66743)

The error looked like it's coming from `turborepo` so I checked their repo and found 2 related issues:
- https://github.com/vercel/turbo/issues/6358
- https://github.com/vercel/turbo/issues/6358

Then I noticed that several new versions of turborepo have been recently published so I assumed there was a regression in those new versions that was causing this error to popup on our side.

Once I locked the version to `1.13.3` (latest stable before those recent updates) the error disappeared.

2024-07-01 23:20 UTC, brunomenezes requested changes

2024-07-01 23:20 UTC, brunomenezes commented on apps/web/src/components/connection/connectionInputStatusBadge.tsx
> +                requestPolicy: "network-only",
Hi @nevendyulgerov, we could remove the `requestPolicy: network-only` because once the input comes to the node, and it gets this status, it is "set in stone", so it has no value making extra n calls (number of table rows) every time we change the page as the result would not change. 

The default request policy is cache-first, so it tries the cache result and only goes to the network in case of a miss.

2024-07-01 23:20 UTC, brunomenezes commented on apps/web/graphql/rollups/queries.graphql
> +  input(index: $index) {
This one is just a comment, not a change request. Even though the filters in the rollups-graphql are a bit limited, I believe we could leverage the `inputs(where:{indexGreaterThan: lower_index-1, indexLowerThan: higher_index+1})` with attention to do a -1 and +1 to the bounds or they would be excluded from the result (kind of a trap). That would make the calls per page (10 or 30 items) to 1 per application of interest in that table page (The ones with connections). However, an architecture change related to UI state management will be needed to ease maintenance. I am adding State Management lib to the work on #165, so let's catch up on that. 

This improvement will come in future iterations.

2024-07-02 00:59 UTC, brunomenezes commented
I did a rebase and pushed. 

cc: @nevendyulgerov

2024-07-02 01:20 UTC, brunomenezes commented on apps/web/src/components/connection/connectionInputStatusBadge.tsx
> +                requestPolicy: "network-only",
Update: I was talking to Guilherme about that, and he asked if `unprocessed` could not be updated to `accepted` as an example. So, I sent a message to the Node-ref team to check the behaviour with accurate information.

2024-07-04 11:32 UTC, nevendyulgerov commented on apps/web/src/components/connection/connectionInputStatusBadge.tsx
> +                requestPolicy: "network-only",
Thanks for those insights @brunomenezes ! I'll make the change as you suggested for now and let's see what the Node-ref team will say.

2024-07-05 00:11 UTC, brunomenezes commented on apps/web/src/components/connection/connectionInputStatusBadge.tsx
> +                requestPolicy: "network-only",
Just to finish the loop. It starts as unprocessed and then moves to one of the available statuses. So, I think we can work with default behaviour rather than always going for the network since it is an update that happens only once.

2024-07-05 00:24 UTC, brunomenezes submitted a review, later dismissed

2024-07-05 14:13 UTC, nevendyulgerov commented on .github/workflows/e2e.yml
> +            - name: Update check status to the outcome
Hi, @brunomenezes , I regards to the failing e2e tests, I was expecting the build to fail with the related e2e job as well, but that was not the case. It was passing ok although the e2e job that we run on sepolia preview url was failing.

Because of this I had to implement this step. It will run the `reportGitHubStatusCheck` script, which will then post a status to the build. That status can be either `success` or `failure` so in the case of the latter the build will fail as well.

2024-07-14 21:55 UTC, brunomenezes approved these changes

2024-07-14 21:55 UTC, merged