#229 Add import and export for specifications
cartesi/rollups-explorer pull request #232
Opened 2024-08-19 14:46 UTC by nevendyulgerov

TBD.

2024-08-26 13:00 UTC, nevendyulgerov commented on .github/workflows/ci.yml
> +                  node-version: 22.6.0
Fix for https://github.com/vercel/next.js/issues/69150. Same issue happens with our build as well.

2024-09-02 02:57 UTC, brunomenezes requested changes
@nevendyulgerov **A rebase is necessary**. I added comments related to the validations that are happening. Also, I got stuck after exporting and trying to re-import my existing specifications.

#### Steps
* Export existing Specifications 
* Then, delete all of them. 
* After trying to import and seeing an error message related to `slice target` that does not exist in my specifications. 
* Nothing happens when I close the error and try to re-import the same file. It is like the button is not working; neither could I see the error again, nor were the specifications loaded.

#### Exported JSON file
[cartesiscan_specifications_export.json](https://github.com/user-attachments/files/16831689/cartesiscan_specifications_export.json)

2024-09-02 02:57 UTC, brunomenezes commented on apps/web/src/components/specification/transfer/validators/v1.ts
> +                        ).some((s) => s.name === specification.sliceTarget)
The [sliceTarget](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/specification/types.ts#L66) is optional even when `sliceInstructions` are present because they're meant for non-standard encoding i.e. `abi.encodePacked`. Therefore, enforcing at least one slice's name that matches the `slice-target` defined will cause problems.

A few test cases to check what I am talking about 

* Case without `sliceTarget` [here](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/test/components/specification/decoder.test.ts#L101)
* Case with `sliceTarget`[here](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/test/components/specification/decoder.test.ts#L146)

2024-09-02 02:57 UTC, brunomenezes commented on apps/web/src/components/specification/transfer/validators/v1.ts
> +                                            : "Invalid slice schema.";
Check the [ SliceInstruction type here](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/specification/types.ts#L40), but the `[name, to , type]` properties are not required even though the `name` is required in the form. Check [this test case ](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/test/components/specification/decoder.test.ts#L146) or the `systemSpecs.ts` file for reference. So importing a good file missing such fields will fail to proceed.

2024-09-02 02:57 UTC, brunomenezes commented on apps/web/src/components/specification/transfer/validators/v1.ts
> +                                        isNonEmptyString(conditionItem.field) &&
As you are also doing a run in the `operators` list below. I think you could check the [inputProperties](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/specification/types.ts#L15) for the `field` property. A rebase with the main is necessary since we merged the #233, and patching is necessary when comparing for retro compatibility's sake. There is a function that does that [here](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/specification/conditionals.ts#L66) , it was added in the PR mentioned.

2024-09-02 02:57 UTC, brunomenezes commented on apps/web/test/components/specification/stubs.ts
> +    timestamp: new Date().getTime(),
This is just a warning. Checking that property in a "deterministic" way may break your test.

2024-09-16 14:29 UTC, brunomenezes commented
@nevendyulgerov I opened a PR against this branch-PR #242. Because I noticed a problem with Specifications showing up, and after refreshing the page, they're gone (recording below). I would suggest the import/export button be the default variant so it follows all the other buttons' look and feel (e.g. `Connect wallet`, `New` etc).



![2024-09-16 10 23 35](https://github.com/user-attachments/assets/15345890-29f9-4f80-b096-e5106c033595)

2024-09-23 21:28 UTC, brunomenezes approved these changes

2024-09-24 11:28 UTC, merged