#21 Create form for sending raw input to application
cartesi/rollups-explorer pull request #36
Opened 2023-10-10 19:05 UTC by nevendyulgerov

2023-10-31 14:38 UTC, tuler commented
My VSCode is detecting some code format differences.

2023-11-01 10:33 UTC, nevendyulgerov commented on apps/web/src/app/shell.tsx
Initially I did this, however it led to coupling between `apps/web` and `packages/ui` due to the following reasons:

- `useApplicationsQuery` is exposed from `web/src/graphql` so it must be imported in `RawInputForm`
- `RawInputForm` must be wrapped by HOC `withUrqlClient`, available from `next-urql` in order for the query to work. Otherwise, you'll get a `No client has been specified using urql's Provider`error, when opening the `RawInputForm`. A `url` param must be passed to `withUrqlClient`. We have it, however, it's an env var again located in `web/.env`

So, with those constraints, I opted for just passing `applications` (and `tokens`) as props to the forms that require them. Otherwise, `RawInputForm` won't be as abstract as we need it, being part of `packages/ui`.

For the time being, I implemented the above two points for `RawInputForm` to demonstrate the coupling issues. I think using props results in cleaner and less coupled code.

2023-11-01 10:35 UTC, nevendyulgerov commented
> My VSCode is detecting some code format differences.

This should be fine. I'm using latest stable version of IntelliJ WebStorm with `prettier` enabled. I typically run `yarn prettier --write .` before making commits so all files should be formatted according to prettier config in the repo.

2023-11-02 18:33 UTC, tuler commented on packages/ui/src/RawInputForm.tsx
> +export const RawInputForm: FC<RawInputFormProps> = (props) => {
I think the branch is not updated.
I see a lot of code formatting issue, and I don't see the `useForm`.
Also don't understand why we need `next-urql` lib.

2023-11-03 06:35 UTC, nevendyulgerov commented on packages/ui/src/RawInputForm.tsx
> +export const RawInputForm: FC<RawInputFormProps> = (props) => {
@tuler I wrote about this under another of your comments. I'll paste my response here as well:

Initially I did this, however it led to coupling between apps/web and packages/ui due to the following reasons:

useApplicationsQuery is exposed from web/src/graphql so it must be imported in RawInputForm
RawInputForm must be wrapped by HOC withUrqlClient, available from next-urql in order for the query to work. Otherwise, you'll get a No client has been specified using urql's Providererror, when opening the RawInputForm. A url param must be passed to withUrqlClient. We have it, however, it's an env var again located in web/.env. On top of that we also have to install next-urql package to make all of this work.
So, with those constraints, I opted for just passing applications (and tokens) as props to the forms that require them. Otherwise, RawInputForm won't be as abstract as we need it, being part of packages/ui.

For the time being, I implemented the above two points for RawInputForm to demonstrate the coupling issues. I think using props results in cleaner and less coupled code.

2023-11-08 23:35 UTC, brunomenezes commented
> Hi @tuler , in regards to:
> 
> > My VSCode is detecting some code format differences.
> 
> This should be fine. I'm using latest stable version of IntelliJ WebStorm with `prettier` enabled and applying reformatting on save. Also, I typically run `yarn prettier --write .` before making commits so all files should be formatted according to prettier config in the repo.

@nevendyulgerov, I noticed that when I entered the files you wrote and made and saved some changes, I saw the import section changing and doing some cmd+z/cmd+shift+z to go back and forth I noticed it organizing the imports. So, I think your Webstorm is just missing the `organizeImports` equivalent that you can see [here](https://github.com/cartesi/rollups-explorer/blob/main/.vscode/settings.json#L7); that option and the `fixAll` do nice things; The first organize things alphabetically and with hierarchy applied on the right-hand side of the import too, and, the latter automatically remove non-used imports so we will avoid having the same avalanche of warnings of non-used things we have on `Staking`.

2023-11-09 00:41 UTC, brunomenezes commented on apps/web/src/app/shell.tsx
Hey @nevendyulgerov,

I have two things to mention here. I agree with @tuler about the header shell fetching this kind of data. I think you could have a `<Deposit />` that encapsulates all the data needs of the form/forms (see where I am getting here? based on the suggestion on #44 ). The other thing that needs to be addressed is that `useApplicationsQuery` going with no limits will soon reach the imposed cardinalities in the backend. That will return errors like `response might exceed the size limit`. I also worked with application IDs and mentioned what I did on my current open PR #41. 

So my suggestions are : 

* Encapsulate your needs in a separate Component using the fetching data, modal and form/forms inside it
* look in my PR and adjust the query graphQL (that will come with my PR merged) and use the limit for requesting only X amount of items to be more future-proof.

2023-11-09 00:47 UTC, brunomenezes requested changes
😞 Sorry! I added comments and forgot about the `Finish your review` box. My requested changes are [here](https://github.com/cartesi/rollups-explorer/pull/36#discussion_r1387348732). The second bullet point is critical as it will cause errors very soon.

2023-11-09 13:28 UTC, nevendyulgerov commented on apps/web/src/app/shell.tsx
Hey @brunomenezes , I created a separate issue for the first point. If you don't mind, I'd like to tackle this separately from this feature so that we keep compact. I'll look into the second point and address it as part of this PR. Please let me know if this works for you.

2023-11-10 03:17 UTC, tuler approved these changes

2023-11-10 04:04 UTC, brunomenezes requested changes

2023-11-10 09:16 UTC, nevendyulgerov commented on apps/web/src/app/shell.tsx
> +            limit: 1000,
Hi @brunomenezes ,

As we discussed over discord, I'll make a separate PR for this type of change. That PR will use the current branch as base. I'll appreciate if we can get the ball rolling on this one and not delay it any further or block it because of that "child" PR, where I'll address your query-related feedback.

2023-11-10 10:15 UTC, nevendyulgerov commented on apps/web/src/app/shell.tsx
> +            limit: 1000,
PR for this ☝️ is https://github.com/cartesi/rollups-explorer/pull/55. It uses [this one](https://github.com/cartesi/rollups-explorer/pull/36) as base, however it's also connected to https://github.com/cartesi/rollups-explorer/issues/53. This means that https://github.com/cartesi/rollups-explorer/pull/36 is not depending on https://github.com/cartesi/rollups-explorer/pull/55 and thus the former shouldn't be blocked because of the latter.

2023-12-10 23:56 UTC, brunomenezes commented
@nevendyulgerov, 
Is this ready to be reviewed from an implementation perspective? You do have some rebasing/conflict to solve in the `yarn.lock`, I imagine is because of this `mantine` version bump.

2023-12-10 23:58 UTC, brunomenezes requested changes
@nevendyulgerov, 
Is this ready to be reviewed from an implementation perspective? You do have some rebasing/conflict to solve in the `yarn.lock`, I imagine is because of this `mantine` version bump.

I am adding the`request changes` to visually show I already started looking into that.

2023-12-11 08:03 UTC, nevendyulgerov commented
> @nevendyulgerov, Is this ready to be reviewed from an implementation perspective? You do have some rebasing/conflict to solve in the `yarn.lock`, I imagine is because of this `mantine` version bump.
> 
> I am adding the`request changes` to visually show I already started looking into that.

Hey, @brunomenezes , yes, this one is ready for code review.

2023-12-20 04:19 UTC, brunomenezes approved these changes

2023-12-20 04:21 UTC, merged