#20 Create form for depositing ether to selected dapp
cartesi/rollups-explorer pull request #40
Opened 2023-10-26 14:55 UTC by nevendyulgerov

2023-10-31 14:43 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +export const EtherDepositForm: FC<EtherDepositFormProps> = (props) => {
Try to use `useForm`. Same comment as the one I left in PR #36

2023-11-02 11:25 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +export const EtherDepositForm: FC<EtherDepositFormProps> = (props) => {
Hi, @tuler , I utilised `useForm` as you requested.

2023-11-02 11:27 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +
We can ignore this warning, as adding `form` as dependency results in infinite resetting of the form when the deposit has succeeded.

2023-11-02 18:19 UTC, tuler reviewed
I don't see the field for the ether amount to deposit

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +            hexExecLayerData: toHex(values.execLayerData),
call the field `execLayerData` instead of `hexExecLayerData`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                : "0x1",
use `zeroAddress` as default value instead of `0x1`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +    const depositPrepare = usePrepareEtherPortalDepositEther({
name this var simply `prepare`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +    const deposit = useEtherPortalDepositEther(depositPrepare.config);
name this var `execute`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +    const depositWait = useWaitForTransaction(deposit.data);
name this var simply `wait`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +            form.reset();
I don't think we need this logic of resetting

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                    onChange={(application) => {
don't handle this manually, let the form handle it.
pass `{...form.getInputProps("application")}` to the `Autocomplete`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                    error={
we don't need this

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                    value={application.value}
don't handle this manually, let the form handle it.
pass {...form.getInputProps("application")} to the Autocomplete

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +    const { applications, onSubmit } = props;
I don't think we need this `onSubmit` callback

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                    isHex(application.value) &&
Use `address != zeroAddress`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                    !applications.includes(application.value) && (
use `address`

2023-11-02 18:25 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                <Textarea
We should hide this under an `Advanced` option, like I did in the ERC-20 deposit form

2023-11-03 07:43 UTC, nevendyulgerov commented
> I don't see the field for the ether amount to deposit

@tuler I'm not sure how to pass the amount to the deposit hook. Looking at https://next.docs.cartesi.io/cartesi-rollups/api/json-rpc/portals/EtherPortal/#depositether I don't see information about the deposit amount. Can you please elaborate how this can be done?

CC @brunomenezes

2023-11-03 07:54 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +    const { applications, onSubmit } = props;
@tuler , I'm using the `onSubmit` callback from the `shell` to refresh the page on successful deposit so that the homepage table get's updated accordingly. If you think this is not required, I'll remove this logic.

2023-11-03 07:58 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +                    !applications.includes(application.value) && (
@tuler , this won't work as expected because the applications array contains addresses in format `0x60a7048c3136293071605a4eaffef49923e981cc` while the `getAddress` util returns addresses in format `0x60A7048C3136293071605A4eAFfeF49923E981cc`. So the check `applications.includes(address)` will always return `false` and present the alert even when you select an application from the list. Here's a video demonstrating this:

https://github.com/cartesi/rollups-explorer/assets/6005179/3176c26d-b5b2-4c57-9a0c-9cba79fd0a6b

2023-11-03 08:55 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +            form.reset();
@tuler , with this logic on successful deposit, the form's inputs get cleared, which is a standard on submit behaviour. Still, if you think we don't need it, I'll remove this logic.

2023-11-03 08:58 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +                    error={
@tuler can you please elaborate why we don't need an error for the applications autocomplete? Looking at `ERC20DepositForm` I see we have similar error handling for `TokenAutocomplete`. Also, since sepolia requests are failing a lot with 503 errors, keeping the `error` field allows users to see those errors.

2023-11-03 13:01 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +    const { applications, onSubmit } = props;
Yeah, I don't think it's required

2023-11-03 13:02 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                    !applications.includes(application.value) && (
You have a two options. Compare ignoring case. Or convert everything to checksummed address using `getAddress`

2023-11-09 00:57 UTC, tuler commented on apps/web/src/app/shell.tsx
> +    const router = useRouter();
this variable is unused

2023-11-09 00:57 UTC, tuler commented on apps/web/src/app/shell.tsx
> +import CartesiLogo from "../components/cartesiLogo";
please organize imports

2023-11-09 00:57 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +            amountBigint:
you can call the variable `amount` only

2023-11-09 00:57 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +                values.amount !== "" ? BigInt(values.amount) : undefined,
this conversion from the filled string to BigInt is not correct. You have to convert using viem `parseUnits`.
The number of decimals is given ideally by querying the native currency of the connected chain.

```typescript
const { chain } = useNetwork();
...
parseUnits(values.amount, chain?.nativeCurrency.decimals ?? 18)
```

2023-11-09 00:57 UTC, tuler commented on packages/ui/src/EtherDepositForm.tsx
> +    }, [wait.status]);
So add the form here to get rid of the warning

2023-11-09 13:16 UTC, nevendyulgerov commented on packages/ui/src/EtherDepositForm.tsx
> +    }, [wait.status]);
The form doesn't have a stable reference and this will result in infinite re-invocation of that effect.

2023-11-10 03:17 UTC, tuler approved these changes

2023-11-10 14:19 UTC, dandheedge requested changes

2023-11-10 14:19 UTC, dandheedge commented on packages/ui/test/EtherDepositForm.test.tsx
> +import { useNetwork } from "wagmi";
This import is unused, I think we can remove it

2023-11-13 07:17 UTC, nevendyulgerov commented on packages/ui/test/EtherDepositForm.test.tsx
> +import { useNetwork } from "wagmi";
Good catch, I addressed this, @dandheedge .

2023-11-14 04:20 UTC, dandheedge approved these changes
LGTM!

2023-11-14 05:41 UTC, merged