39. Improve ERC20Portal data display
cartesi/rollups-explorer pull request #42
Opened 2023-11-01 09:05 UTC by dandheedge

Close #39

2023-11-02 11:36 UTC, nevendyulgerov approved these changes

2023-11-02 18:53 UTC, tuler commented on apps/web/src/components/inputRow.tsx
> +    const isERC20Method = slice(payload, 0, 1) === "0x01";
This logic is not correct. It's not the first byte as `0x01` that indicates the payload is a ERC-20 deposit. It's the sender of the input.

2023-11-03 01:08 UTC, brunomenezes requested changes
There are some requested changes to be addressed as pointed by @tuler

2023-11-03 06:53 UTC, dandheedge commented
> There are some requested changes to be addressed as pointed by @tuler

@brunomenezes I added the second params on `decodePayload` to check whether the sender address of the input is the  `erc20PortalAddress`

2023-11-09 01:23 UTC, tuler reviewed
Instead of doing a specific change for ERC-20 deposits I'd rather handle this in the scope of the more general problem of how to present different kinds of binary data.

2023-11-09 22:12 UTC, closed without merging