56. Fix the logical condition for displaying the warning.
cartesi/rollups-explorer pull request #69
Opened 2023-11-21 09:05 UTC by dandheedge

Close #56

2023-11-22 08:45 UTC, nevendyulgerov commented on packages/ui/src/ERC20DepositForm.tsx
> +export const isFirstDeposit = (erc20Address: string, data: string[]) => {
I suggest that we simplify the util in this way:

```
const checkFirstDeposit = (erc20Address: string, data: string[]) =>
    isAddress(erc20Address) &&
    !data.some((contract) => isAddressEqual(contract as Address, erc20Address));
```

This version of the util should work fine for application addresses. For tokens, we can do this:

```
// inside TokenAutocomplete component
const tokenAddresses = useMemo(
    () => tokens.map((t) => t.substring(t.indexOf("0x"))),
    [tokens],
);
...
{checkFirstDeposit(erc20Address, tokenAddresses) && (
    <Alert variant="light" color="yellow" icon={<TbAlertCircle />}>
        This is the first deposit of that token.
    </Alert>
)}
```

Also, you may want to extract `checkFirstDeposit` function in `/src/utils` folder, because we'll probably want to use it in other components like EtherDeposit or RawInput.

2023-11-23 04:04 UTC, brunomenezes commented
@dandheedge, Rebase the PR. The #54 was merged.

2023-11-27 00:29 UTC, brunomenezes commented on packages/ui/src/ERC20DepositForm.tsx
> +export const isFirstDeposit = (erc20Address: string, data: string[]) => {
Honestly, guys, I think the ideal solution is a quick ping on the graphQL API for both `Applications` and `Tokens`. I mentioned before that we can provide a pre-filled autocomplete list with 10 ~ 15 items and fire the correct query on input change. That will save us from all the logic involved here—Subsquid `where clause` is quite flexible. 

Here is a reference of one I did for `Dapp Connect` feature, but I do understand they are components living in different packages, and one has direct access to things the other doesn't and that is ok. Because it is just a matter of improving the lifecycle of the component API coming from the `packages/ui`. [code ref](https://github.com/cartesi/rollups-explorer/blob/main/apps/web/src/components/connectionForm.tsx#L110) 


cc: @nevendyulgerov, @dandheedge

2023-12-12 05:34 UTC, dandheedge commented on packages/ui/src/ERC20DepositForm.tsx
> +export const isFirstDeposit = (erc20Address: string, data: string[]) => {
In the most recent commit, I've implemented hooks to retrieve applications and tokens using GraphQL. This allows the component to access the necessary data

@brunomenezes @nevendyulgerov

2023-12-14 18:15 UTC, nevendyulgerov commented on packages/ui/src/ERC20DepositForm.tsx
> +    useEffect(() => {}, [tokens]);
Empty effect, please remove it if you don't need it.

2023-12-14 18:19 UTC, nevendyulgerov commented on apps/web/src/components/shell.tsx
> +    const changeTokenQuery = (address: string) => {
Hey, @dandheedge , this implementation relies on the `Shell` component holding applications and tokens state for the forms. However, with https://github.com/cartesi/rollups-explorer/pull/36/files this will significantly change so that a new `SendTransaction` component controls these states.

Due to this, I recommend that you use https://github.com/cartesi/rollups-explorer/pull/36 as base for your changes here, so that we can sync up on the touching pieces between your branch and `feature/21-create-form-for-sending-raw-input-to-application`. Otherwise, we'll have a bad time resolving conflicts regardless who merges their PR first.

2024-01-14 21:33 UTC, brunomenezes commented on packages/ui/src/ERC20DepositForm.tsx
> +    useEffect(() => {}, [tokens]);
@nevendyulgerov, start the review and mark it as `Request changes` for signalling.

2024-01-18 00:15 UTC, brunomenezes requested changes
Hey @dandheedge, I tested these changes, and now the copy/paste is working for the application and token address inputs for the ERC-20 deposit. Still, if I select an item in the autocomplete for the token, it displays the warning right away 😕. Have a look at the gif below. 



![autocomplete-selection-displays-warning](https://github.com/cartesi/rollups-explorer/assets/1239768/904220c7-2d37-4d59-8684-fbd7668779f0)

2024-01-30 01:04 UTC, brunomenezes approved these changes

2024-01-30 01:07 UTC, merged